name: pre-commit

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pre-commit environments
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-
      continue-on-error: true

    - name: Install pre-commit (fallback)
      if: failure()
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      continue-on-error: false
      env:
        # Reduce memory usage for pre-commit
        PRE_COMMIT_COLOR: never
